### ISSUE TITLE
ASN38370 duplicate

### ISSUE THREAD

**Issue by lo0pback-404** [cmdshell/HomeLab#1]
telecom和mobile都存在ASN38370，这个应该是归属铁通（移动）的ASN。

**Comment by sungtime** [comment]
已经fix，thanks
看看release文件需要什么格式的，txt还是rsc还是直接路由条目比较好？

> telecom和mobile都存在ASN38370，这个应该是归属铁通（移动）的ASN。

**Comment by lo0pback-404** [comment]
> 已经fix，thanks 看看release文件需要什么格式的，txt还是rsc还是直接路由条目比较好？
> 
> > telecom和mobile都存在ASN38370，这个应该是归属铁通（移动）的ASN。

建议是txt就可以，通用性强一点。

**Comment by sungtime** [comment]
> > 已经fix，thanks 看看release文件需要什么格式的，txt还是rsc还是直接路由条目比较好？
> > > telecom和mobile都存在ASN38370，这个应该是归属铁通（移动）的ASN。
> 
> 建议是txt就可以，通用性强一点。

txt里面是ip还是路由条目？
其实配合bird的收表然后在ros上利用bgp属性做过滤是最灵活的方式应该

**Comment by lo0pback-404** [comment]
> > > 已经fix，thanks 看看release文件需要什么格式的，txt还是rsc还是直接路由条目比较好？
> > > > telecom和mobile都存在ASN38370，这个应该是归属铁通（移动）的ASN。
> > 
> > 
> > 建议是txt就可以，通用性强一点。
> 
> txt里面是ip还是路由条目？ 其实配合bird的收表然后在ros上利用bgp属性做过滤是最灵活的方式应该

我觉得txt放asn号就可以，IP路由网上现成的太多了。

**Comment by sungtime** [comment]
已经建立github action自动构建asn包括cn和noncn常见ISP及互联网提供商

**Comment by sungtime** [comment]
已经建立github action自动构建asn包括cn和noncn常见ISP及互联网提供商
